### PR TITLE
use commit sha as version of go library

### PR DESCRIPTION
**Pull request by willnorris**

### CODE REVIEW

**Comment by dissolve** [comment]
Hmm, really don't like that this assumes a path on the local machine.

Just hacking something together really quick, but what about something like this?

`
curl -s 'https://github.com/willnorris/microformats/commits/master' |grep 'sha btn' | head -n1 |sed 's/.*commit\///'|cut -c 1-7`

**Comment by dissolve** [comment]
actually, dug in to this more, I was thinking you were using a local dir of yours.  this doesn't work on my system, $GOPATH is empty, it is searching for ~/src/... but the actual dir is ~/go/src/....

**Comment by dissolve** [comment]
does 

`git -C $(go env GOPATH)/src/willnorris.com/go/microformats rev-parse --short HEAD 2>/dev/null`

work for you?

**Comment by willnorris** [comment]
ah, yes... that's better.  The fallback to HOME, `${GOPATH:-$HOME}` was because I seemed to remember that the default GOPATH was `~/`.  Looks like it's actually `~/go`.  But your use of `go env` is definite the better way to handle this.  Thanks!

PR updated.

**Pull request merged**
